### ISSUE TITLE
[Email 2024 06 06] invaziniu rusiu israsus automatiskai patvirtinti

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-rusys-api#53]
Jei yra pasirinkta **Gauti išrašą** ir **Rūšių tipas yra invazinė**, tuomet prašymas būtų patvirtinamas automatiškai.
![Image](https://github.com/user-attachments/assets/243a4045-f03e-466b-8feb-1723de1282a8)

**Comment by IngaPauliuniene** [comment]
Neteisingai rašoma data, kuomet yra automatiškai patvirtinama paprasto naudotojo aplinkoje.
![Image](https://github.com/user-attachments/assets/17542482-08e3-4eec-b8c3-3b9886608e68)
